### GET ALL CONTENT
GET http://localhost:8080/api/content


### GET SINGLE CONTENT
GET http://localhost:8080/api/content/6

### POST CONTENT
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "title": "Created Title",
  "description": "Created Description",
  "status": "IDEA",
  "ContentType": "ARTICLE",
  "url": "https://example.com"
}


### PUT CONTENT
PUT http://localhost:8080/api/content/6
Content-Type: application/json

{
  "title": "Updated Title",
  "description": "Updated Description",
  "status": "IDEA",
  "ContentType": "ARTICLE",
  "url": "https://example.com"
}


### DELETE CONTENT
DELETE http://localhost:8080/api/content/6


###H2 DATABASE
http://localhost:8080/h2-console